# This file lists the dependencies needed to build and test all of svgdigitizer.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: svgdigitizer-build
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - black
  - click
  - isort
  - matplotlib-base
  - myst-parser
  - pandas
  - pdf2image
  - pillow
  - poppler
  - pylint
  - pytest
  - pyyaml
  - scipy
  - sphinx
  - svg.path
  - svgpathtools
  - svgwrite
  - pip
  - pip:
    - linkchecker
    - sphinx_rtd_theme
    - datapackage
