# This file lists the dependencies needed to build and test all of svgdigitizer.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: svgdigitizer-build
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - black
  - click>=8,<9
  - isort
  - matplotlib-base>=3.5,<4
  - myst-parser>=0.16,<0.17
  - pandas>=1.3,<2
  - pdf2image>=1.16,<2
  - pillow>=8.4,<9
  - poppler>=22,<23
  - pylint>=2.12,<3
  - pytest>=6.2,<7
  - pyyaml>=6,<7
  - scipy>=1.7,<2
  - sphinx>=4.3,<5
  - svg.path>=4.1,<5
  - svgpathtools>=1.4,<2
  - svgwrite>=1.4,<2
  - pip>=21,<22
  - pip:
    - linkchecker>=10.1,<11
    - sphinx_rtd_theme>=1,<2
    - datapackage>=1.15,<2
