# This file lists the dependencies needed to build and test all of svgdigitizer.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: svgdigitizer-build
channels:
  - conda-forge
  - defaults
dependencies:
  - svg.path
  - matplotlib-base
  - pandas
  - click
  - pyyaml
  - pillow
  - pdf2image
  - svgwrite
  - svgpathtools
  - pycodestyle
