name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: install svgdigitizer
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: doctest
        shell: bash -l {0}
        run: |
          pytest --doctest-modules svgdigitizer
      - name: cli-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/xy.svg
          diff test/data/xy.csv test/data/xy.csv.expected
      - name: scalebar-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/scaling_factor.svg
          diff test/data/scaling_factor.csv test/data/scaling_factor.csv.expected
      - name: sampling-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/sampling.svg --sampling_interval 1
          diff test/data/sampling.csv test/data/sampling.csv.expected
      - name: sampling-many-points-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/sampling_many_points.svg --sampling_interval 1
          diff test/data/sampling_many_points.csv test/data/sampling_many_points.csv.expected
      - name: unit-test
        shell: bash -l {0}
        run: |
          python -m test.test_regex
