name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: install svgdigitizer
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: doctest
        shell: bash -l {0}
        run: |
          pytest --doctest-modules svgdigitizer
      - name: cli-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/xy.svg
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/xy.csv"), pandas.read_csv("test/data/xy.csv.expected"))'
      - name: scalebar-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/scaling_factor.svg
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/scaling_factor.csv"), pandas.read_csv("test/data/scaling_factor.csv.expected"))'
      - name: sampling-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/sampling.svg --sampling_interval 1
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/sampling.csv"), pandas.read_csv("test/data/sampling.csv.expected"))'
      - name: sampling-many-points-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/sampling_many_points.svg --sampling_interval 1
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/sampling_many_points.csv"), pandas.read_csv("test/data/sampling_many_points.csv.expected"))'
      - name: no-layer-test
        shell: bash -l {0}
        run: |
          svgdigitizer digitize test/data/svg_without_layer.svg
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/svg_without_layer.csv"), pandas.read_csv("test/data/svg_without_layer.csv.expected"))'
      - name: cv-test
        shell: bash -l {0}
        run: |
          svgdigitizer cv test/data/xy_rate.svg --metadata test/data/xy_rate.yaml
          diff test/data/xy_rate.json test/data/xy_rate.json.expected
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/xy_rate.csv"), pandas.read_csv("test/data/xy_rate.csv.expected"))'
      - name: cv-test-without-metadata
        shell: bash -l {0}
        run: |
          svgdigitizer cv test/data/xy_rate_without_metadata.svg
          diff test/data/xy_rate_without_metadata.json test/data/xy_rate_without_metadata.json.expected
          python -c 'import pandas; pandas.testing.assert_frame_equal(pandas.read_csv("test/data/xy_rate_without_metadata.csv"), pandas.read_csv("test/data/xy_rate_without_metadata.csv.expected"))'
